export async function onRequest(){
  const html=`<!DOCTYPE html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Painel de IA</title><style>
  :root{--bg:#070a13;--panel:rgba(255,255,255,.075);--line:rgba(255,255,255,.14);--text:#f8efe1;--muted:#c8bba8;--gold:#f1c46f;--ok:#7de7a5;--err:#ff7b8c;--warn:#ffd27d}*{box-sizing:border-box}body{margin:0;min-height:100dvh;font-family:Inter,system-ui,sans-serif;color:var(--text);background:radial-gradient(circle at 15% 0,rgba(241,196,111,.18),transparent 32rem),linear-gradient(145deg,#05070e,#0b1020 60%,#070811);padding:18px}.wrap{width:min(1100px,100%);margin:auto}.hero,.card,.toolbar{background:linear-gradient(145deg,rgba(255,255,255,.105),rgba(255,255,255,.045));border:1px solid var(--line);box-shadow:0 28px 90px rgba(0,0,0,.45),inset 0 1px 0 rgba(255,255,255,.13);backdrop-filter:blur(20px);border-radius:28px}.hero{padding:24px;margin-bottom:14px}.eyebrow{display:inline-flex;margin-bottom:10px;padding:7px 10px;border-radius:999px;color:var(--gold);border:1px solid rgba(241,196,111,.28);background:rgba(241,196,111,.08);font-size:.72rem;font-weight:900;letter-spacing:.12em;text-transform:uppercase}h1{font-size:clamp(2rem,6vw,4rem);letter-spacing:-.06em;line-height:.95;margin:0}.hero p,.muted{color:var(--muted);line-height:1.55}.toolbar{padding:14px;display:grid;grid-template-columns:1fr auto auto;gap:10px;align-items:center;margin-bottom:14px}input,button{min-height:48px;border-radius:999px;border:1px solid var(--line);padding:0 14px;font:inherit}input{background:rgba(255,255,255,.08);color:var(--text)}button{font-weight:900;background:linear-gradient(135deg,var(--gold),#d89a43);color:#161009;cursor:pointer}.secondary{background:rgba(255,255,255,.08);color:var(--text)}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:14px}.stat{padding:14px;border-radius:20px;background:rgba(255,255,255,.055);border:1px solid var(--line)}.stat strong{display:block;font-size:1.5rem}.stat span{color:var(--muted);font-size:.82rem}.list{display:grid;gap:10px}.card{padding:16px}.card-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.provider{font-weight:950;font-size:1.05rem}.badge{display:inline-flex;padding:6px 10px;border-radius:999px;font-size:.78rem;font-weight:950;border:1px solid var(--line)}.ok{color:var(--ok);background:rgba(125,231,165,.08);border-color:rgba(125,231,165,.24)}.error{color:var(--err);background:rgba(255,123,140,.08);border-color:rgba(255,123,140,.24)}.warn{color:var(--warn);background:rgba(255,210,125,.08);border-color:rgba(255,210,125,.24)}.time{color:var(--muted);font-size:.82rem;margin-top:4px}.msg{margin:12px 0 0;color:var(--muted);line-height:1.45}.empty{padding:20px;text-align:center;color:var(--muted)}@media(max-width:760px){.toolbar{grid-template-columns:1fr}.grid{grid-template-columns:1fr 1fr}.card-head{display:block}.badge{margin-top:8px}}
  </style></head><body><main class="wrap"><section class="hero"><div class="eyebrow">Preparatório TGE</div><h1>Painel de IA</h1><p>Veja quais provedores corrigiram, quais falharam e teste as chaves configuradas no Cloudflare.</p></section><section class="toolbar"><input id="pass" type="password" placeholder="Senha administrativa"><button id="load">Carregar logs</button><button class="secondary" id="test">Testar IAs</button></section><section class="grid"><div class="stat"><strong id="total">—</strong><span>logs</span></div><div class="stat"><strong id="oks">—</strong><span>sucessos</span></div><div class="stat"><strong id="errs">—</strong><span>falhas</span></div><div class="stat"><strong id="last">—</strong><span>último teste</span></div></section><div id="out" class="list"><div class="empty">Carregue os logs ou teste as IAs.</div></div></main><script>
  const out=document.getElementById('out');
  const pass=()=>document.getElementById('pass').value;
  function badge(status){if(status==='ok')return '<span class="badge ok">ok</span>'; if(status==='error'||status==='limit_or_error')return '<span class="badge error">erro</span>'; return '<span class="badge warn">aviso</span>'}
  function setStats(items){document.getElementById('total').textContent=items.length;document.getElementById('oks').textContent=items.filter(x=>x.status==='ok').length;document.getElementById('errs').textContent=items.filter(x=>x.status!=='ok').length;document.getElementById('last').textContent=new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}
  function renderLogs(items){setStats(items);out.innerHTML=items.length?items.map(l=>'<article class="card"><div class="card-head"><div><div class="provider">'+(l.provider_name||l.name||'IA')+'</div><div class="time">'+(l.created_at?new Date(l.created_at).toLocaleString('pt-BR'):(l.latencyMs?l.latencyMs+' ms':'Agora'))+'</div></div>'+badge(l.status)+'</div><p class="msg">'+(l.message||'Sem mensagem.')+'</p></article>').join(''):'<div class="empty">Nenhum log encontrado.</div>'}
  document.getElementById('load').onclick=async()=>{out.innerHTML='<div class="empty">Carregando logs...</div>';const res=await fetch('/api/admin/logs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:pass()})});const data=await res.json();if(!res.ok){out.innerHTML='<div class="card"><span class="badge error">erro</span><p class="msg">'+(data.error||'Não foi possível carregar.')+'</p></div>';return}renderLogs(data.logs||[])};
  document.getElementById('test').onclick=async()=>{out.innerHTML='<div class="empty">Testando provedores...</div>';const res=await fetch('/api/admin/test-ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:pass()})});const data=await res.json();if(!res.ok){out.innerHTML='<div class="card"><span class="badge error">erro</span><p class="msg">'+(data.error||'Não foi possível testar.')+'</p></div>';return}renderLogs(data.results||[])};
  </script></body></html>`;
  return new Response(html,{headers:{'Content-Type':'text/html; charset=utf-8'}})
}