const state={mode:null,user:null,token:null,attempt:null,current:0,startedAt:null,timer:null,chatTimer:null,chatOpen:false,lastChatRender:""};
const $=id=>document.getElementById(id);
const els={home:$("home"),simulator:$("simulator"),mainArea:$("mainArea"),userLabel:$("userLabel"),modeLabel:$("modeLabel"),timeLabel:$("timeLabel"),answeredLabel:$("answeredLabel"),coefLabel:$("coefLabel"),questionCounter:$("questionCounter"),questionType:$("questionType"),progressBar:$("progressBar"),questionText:$("questionText"),closedAnswers:$("closedAnswers"),openAnswer:$("openAnswer"),questionNote:$("questionNote"),backQuestionBtn:$("backQuestionBtn"),nextQuestionBtn:$("nextQuestionBtn"),questionMap:$("questionMap"),newAttemptBtn:$("newAttemptBtn"),rankingBtn:$("rankingBtn"),resultPanel:$("resultPanel"),rankingPanel:$("rankingPanel"),resultSummary:$("resultSummary"),finalScore:$("finalScore"),finalClosed:$("finalClosed"),finalOpen:$("finalOpen"),finalCoef:$("finalCoef"),finalAvgTime:$("finalAvgTime"),finalAttemptNo:$("finalAttemptNo"),viewCorrectionBtn:$("viewCorrectionBtn"),fallbackAiBtn:$("fallbackAiBtn"),correctionList:$("correctionList"),rankingList:$("rankingList"),modal:$("modal"),modalContent:$("modalContent"),chatButton:$("chatButton"),chatWindow:$("chatWindow"),closeChatBtn:$("closeChatBtn"),chatMessages:$("chatMessages"),chatForm:$("chatForm"),chatInput:$("chatInput"),chatBadge:$("chatBadge")};
function friendlyError(e){return e?.message||"Não foi possível concluir. Tente novamente."}
async function api(path,options={}){const headers={"Content-Type":"application/json",...(options.headers||{})};if(state.token)headers.Authorization="Bearer "+state.token;const res=await fetch(path,{...options,headers});let data=null;try{data=await res.json()}catch{}if(!res.ok)throw new Error(data?.error||"Não foi possível completar a ação.");return data}
function showModal(html){els.modalContent.innerHTML=html;els.modal.classList.remove("hidden")}
function closeModal(){els.modal.classList.add("hidden")}
function fmt(ms){ms=Math.max(0,Math.round(ms||0));const s=Math.floor(ms/1000),m=Math.floor(s/60),r=s%60;return String(m).padStart(2,"0")+":"+String(r).padStart(2,"0")}
function normalizeName(n){return String(n||"").trim().replace(/\s+/g," ")}
function escapeHtml(v){return String(v||"").replace(/[<>&"]/g,s=>({"<":"&lt;",">":"&gt;","&":"&amp;",'"':"&quot;"}[s]))}
function enter(id,fn){const el=$(id);if(el)el.addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();fn()}})}
function hideGuestFeatures(){els.chatButton.classList.add("hidden");els.chatWindow.classList.add("hidden");els.chatBadge.classList.add("hidden");els.rankingBtn.classList.add("hidden");state.chatOpen=false;clearInterval(state.chatTimer)}
function enableGuestFeatures(){els.chatButton.classList.remove("hidden");els.rankingBtn.classList.remove("hidden");clearInterval(state.chatTimer);loadUnread();state.chatTimer=setInterval(()=>{loadUnread();if(state.chatOpen)loadChat(true)},2000)}
function clearPanels(){els.resultPanel.classList.add("hidden");els.rankingPanel.classList.add("hidden");els.correctionList.classList.add("hidden");els.correctionList.innerHTML=""}
function setHeader(){els.userLabel.textContent=state.user?.displayName||"—";els.modeLabel.textContent=state.mode==="guest"?"Convidado":"Visitante";els.timeLabel.textContent=state.startedAt?fmt(Date.now()-state.startedAt):"00:00";els.answeredLabel.textContent=state.attempt?`${state.attempt.questions.filter(q=>q.locked).length}/${state.attempt.questions.length}`:"0/20";els.coefLabel.textContent=state.attempt?estimatePartialCoef():"0"}

document.querySelectorAll("[data-entry]").forEach(btn=>btn.onclick=()=>openEntry(btn.dataset.entry));
function openEntry(kind){
 if(kind==="visitor"){
  hideGuestFeatures();
  showModal(`<h2>Entrar como Visitante</h2><p>Informe seu nome para começar.</p><div class="field"><label>Nome</label><input id="visitorName" placeholder="Digite seu nome"></div><div class="modal-actions"><button class="btn" id="visitorBack">Voltar</button><button class="btn primary" id="visitorGo">Entrar</button></div>`);
  const go=()=>{const name=normalizeName($("visitorName").value);if(name.length<2)return alert("Digite um nome com pelo menos 2 letras.");state.mode="visitor";state.user={displayName:name};state.token=null;localStorage.setItem("tge_visitor_name",name);closeModal();showDashboard()};
  $("visitorBack").onclick=closeModal;$("visitorGo").onclick=go;enter("visitorName",go);const old=localStorage.getItem("tge_visitor_name");if(old)$("visitorName").value=old;$("visitorName").focus();
 }
 if(kind==="guest"){
  showModal(`<h2>Entrar como Convidado</h2><p>Use o nome e a senha da turma.</p><div class="field"><label>Nome</label><input id="guestName" placeholder="Ex.: João"></div><div class="field"><label>Senha</label><input id="guestPass" type="password" placeholder="Sua senha"></div><div class="modal-actions"><button class="btn" id="guestBack">Voltar</button><button class="btn primary" id="guestGo">Entrar</button></div>`);
  $("guestBack").onclick=closeModal;$("guestGo").onclick=guestLogin;enter("guestName",guestLogin);enter("guestPass",guestLogin);$("guestName").focus();
 }
}
async function guestLogin(){try{const name=normalizeName($("guestName").value),password=$("guestPass").value;if(name.length<2||!password)return alert("Preencha nome e senha.");const data=await api("/api/login",{method:"POST",body:JSON.stringify({name,password})});state.mode="guest";state.user=data.user;state.token=data.token;localStorage.setItem("tge_guest_session",JSON.stringify({token:data.token,user:data.user}));closeModal();enableGuestFeatures();showDashboard()}catch(e){alert(friendlyError(e))}}
function showDashboard(){clearInterval(state.timer);state.attempt=null;state.current=0;state.startedAt=null;els.home.classList.add("hidden");els.simulator.classList.remove("hidden");els.mainArea.classList.add("hidden");clearPanels();setHeader();els.resultPanel.classList.remove("hidden");els.resultPanel.querySelector("h2").textContent=`Painel de ${escapeHtml(state.user?.displayName||"usuário")}`;els.resultSummary.innerHTML="Acompanhe tudo por aqui. O cronômetro só começa quando você iniciar o simulado.";els.finalScore.textContent="—";els.finalClosed.textContent="—";els.finalOpen.textContent="—";els.finalCoef.textContent="—";els.finalAvgTime.textContent="00:00";els.finalAttemptNo.textContent="—";els.viewCorrectionBtn.textContent="Iniciar simulado";els.viewCorrectionBtn.onclick=openReadyModal;els.viewCorrectionBtn.classList.remove("hidden");els.fallbackAiBtn.classList.add("hidden");if(state.mode==="guest"){loadRanking();els.chatWindow.classList.remove("hidden");state.chatOpen=true;loadChat()}else{hideGuestFeatures();els.chatWindow.classList.add("hidden")}}
function openReadyModal(){const isGuest=state.mode==="guest";showModal(`<h2>Estou pronto?</h2><p><b>Instruções:</b> responda todas as questões. Nas fechadas, você pode trocar a alternativa antes de clicar em Próxima. Depois disso, a resposta fica travada.</p><p><b>Coeficiente:</b> considera acertos, erros, peso das abertas, tempo equilibrado e repetição.</p>${isGuest?"<p>O fórum e o ranking continuam disponíveis durante a tentativa.</p>":""}<div class="modal-actions"><button class="btn" id="readyBack">Voltar</button><button class="btn primary" id="readyGo">Estou pronto</button></div>`);$("readyBack").onclick=()=>{closeModal();showDashboard()};$("readyGo").onclick=startAttempt}
async function startAttempt(){try{closeModal();clearPanels();els.home.classList.add("hidden");els.simulator.classList.remove("hidden");els.mainArea.classList.remove("hidden");const endpoint=state.mode==="guest"?"/api/attempt/start":"/api/visitor/start";const seen=state.mode==="visitor"?getVisitorStats():null;const data=await api(endpoint,{method:"POST",body:JSON.stringify({seen})});if(!data?.attempt?.questions)throw new Error("Não consegui montar o simulado. Verifique o banco de questões.");state.attempt=data.attempt;state.current=0;state.startedAt=Date.now();startTimer();render()}catch(e){alert(friendlyError(e));showDashboard()}}
function startTimer(){clearInterval(state.timer);state.timer=setInterval(updateHeader,1000)}
function getVisitorStats(){try{return JSON.parse(localStorage.getItem("tge_visitor_stats")||"{}")}catch{return{}}}
function setVisitorStats(stats){localStorage.setItem("tge_visitor_stats",JSON.stringify(stats))}
function currentQuestion(){return state.attempt?.questions?.[state.current]}
function updateHeader(){if(!state.attempt){setHeader();return}const answered=state.attempt.questions.filter(q=>q.locked).length,total=state.attempt.questions.length,elapsed=Date.now()-state.startedAt;els.userLabel.textContent=state.user?.displayName||"Visitante";els.modeLabel.textContent=state.mode==="guest"?"Convidado":"Visitante";els.timeLabel.textContent=fmt(elapsed);els.answeredLabel.textContent=`${answered}/${total}`;els.coefLabel.textContent=estimatePartialCoef()}
function estimatePartialCoef(){if(!state.attempt)return 0;let points=0,max=0;state.attempt.questions.forEach(q=>{if(q.kind==="open")max+=2;else{max+=1;if(q.locked&&q.isCorrect)points+=1}});return max?Math.round(points/max*100):0}
function render(){if(!state.attempt)return;updateHeader();const q=currentQuestion(),total=state.attempt.questions.length;q.viewStartedAt=q.viewStartedAt||Date.now();els.questionCounter.textContent=`Questão ${state.current+1} de ${total}`;els.questionType.textContent=q.kind==="open"?"Aberta":"Fechada";els.progressBar.style.width=`${(state.current+1)/total*100}%`;els.questionText.textContent=q.prompt;els.closedAnswers.innerHTML="";els.openAnswer.value=q.answerText||"";els.openAnswer.classList.toggle("hidden",q.kind!=="open");els.closedAnswers.classList.toggle("hidden",q.kind==="open");if(q.kind==="closed"){q.options.forEach((opt,idx)=>{const btn=document.createElement("button");btn.className="answer";if(q.selectedOptionId===opt.id)btn.classList.add("selected");if(q.locked)btn.classList.add("locked");if(q.locked&&q.resultKnown){if(opt.id===q.correctOptionId)btn.classList.add("good");if(q.selectedOptionId===opt.id&&!q.isCorrect)btn.classList.add("bad")}btn.innerHTML=`<span class="letter">${String.fromCharCode(65+idx)}</span><span>${escapeHtml(opt.text)}</span>`;btn.onclick=()=>{if(q.locked)return;q.selectedOptionId=opt.id;render()};els.closedAnswers.appendChild(btn)})}els.questionNote.textContent=q.locked?(q.kind==="closed"?(q.resultKnown?(q.isCorrect?"Você acertou esta questão.":"Você errou esta questão."):"Resposta travada."):"Resposta aberta travada. A IA corrigirá no final."):(q.kind==="closed"?"Você pode trocar a alternativa antes de clicar em Próxima.":"Você não pode deixar a resposta aberta em branco.");els.backQuestionBtn.disabled=state.current===0;els.nextQuestionBtn.textContent=state.current===total-1?"Finalizar":"Próxima";renderMap()}
function renderMap(){els.questionMap.innerHTML="";state.attempt.questions.forEach((q,i)=>{const chip=document.createElement("button");chip.className="qchip";chip.textContent=i+1;if(i===state.current)chip.classList.add("now");if(q.locked)chip.classList.add("answered");if(q.kind==="closed"&&q.resultKnown)chip.classList.add(q.isCorrect?"good":"bad");chip.onclick=()=>{state.current=i;render()};els.questionMap.appendChild(chip)})}
els.openAnswer.addEventListener("input",()=>{const q=currentQuestion();if(q&&!q.locked)q.answerText=els.openAnswer.value});
els.backQuestionBtn.onclick=()=>{if(state.current>0){state.current--;render()}};
els.nextQuestionBtn.onclick=async()=>{try{const q=currentQuestion();if(!q.locked){if(q.kind==="closed"&&!q.selectedOptionId)return alert("Marque uma alternativa para continuar.");if(q.kind==="open"&&!normalizeName(els.openAnswer.value))return alert("Digite sua resposta para continuar.");await lockCurrentQuestion()}if(state.current<state.attempt.questions.length-1){state.current++;render()}else await finishAttempt()}catch(e){alert(friendlyError(e))}};
async function lockCurrentQuestion(){const q=currentQuestion();const timeMs=Date.now()-(q.viewStartedAt||Date.now());if(state.mode==="guest"){const payload=q.kind==="closed"?{attemptId:state.attempt.id,questionAttemptId:q.attemptQuestionId,kind:q.kind,selectedOptionId:q.selectedOptionId,timeMs}:{attemptId:state.attempt.id,questionAttemptId:q.attemptQuestionId,kind:q.kind,answerText:els.openAnswer.value,timeMs};const res=await api("/api/attempt/answer",{method:"POST",body:JSON.stringify(payload)});Object.assign(q,res.question)}else{const res=await api("/api/visitor/check",{method:"POST",body:JSON.stringify({questionId:q.id,selectedOptionId:q.selectedOptionId})});q.locked=true;q.resultKnown=true;q.isCorrect=res.isCorrect;q.correctOptionId=res.correctOptionId;q.timeMs=timeMs;updateVisitorStats(q)}}
function updateVisitorStats(q){const stats=getVisitorStats();stats[q.id]=stats[q.id]||{seen:0,wrong:0,totalTime:0};stats[q.id].seen++;if(!q.isCorrect)stats[q.id].wrong++;stats[q.id].totalTime+=q.timeMs||0;setVisitorStats(stats)}
async function finishAttempt(){const missing=state.attempt.questions.find(q=>!q.locked);if(missing)return alert("Responda todas as questões antes de finalizar.");if(state.mode==="guest"){const res=await api("/api/attempt/finish",{method:"POST",body:JSON.stringify({attemptId:state.attempt.id})});state.attempt.result=res.result;showResult(res)}else showResult({result:buildVisitorResult()})}
function buildVisitorResult(){const qs=state.attempt.questions,closedOk=qs.filter(q=>q.isCorrect).length,totalTime=Date.now()-state.startedAt,score=Math.round(closedOk/qs.length*100)/10;return{score,closedScore:closedOk,closedTotal:qs.length,openScore:0,openTotal:0,coefficient:Math.round(closedOk/qs.length*100),avgTimeMs:totalTime/qs.length,attemptNumber:1,corrections:qs.map((q,i)=>({order:i+1,kind:"closed",prompt:q.prompt,selectedOptionId:q.selectedOptionId,correctOptionId:q.correctOptionId,isCorrect:q.isCorrect,options:q.options}))}}
function showResult(res){clearInterval(state.timer);els.mainArea.classList.add("hidden");const r=res.result;els.resultPanel.classList.remove("hidden");els.resultPanel.querySelector("h2").textContent="Resultado";els.finalScore.textContent=r.score;els.finalClosed.textContent=`${r.closedScore}/${r.closedTotal}`;els.finalOpen.textContent=`${r.openScore}/${r.openTotal}`;els.finalCoef.textContent=r.coefficient;els.finalAvgTime.textContent=fmt(r.avgTimeMs);els.finalAttemptNo.textContent=r.attemptNumber||"-";els.resultSummary.textContent=r.fallbackPrompt?"A IA atingiu o limite. Você pode corrigir suas abertas em outra IA usando o botão abaixo.":"Tentativa finalizada. Veja suas métricas e a correção quando quiser.";els.fallbackAiBtn.classList.toggle("hidden",!r.fallbackPrompt);if(r.fallbackPrompt){els.fallbackAiBtn.onclick=()=>openFallbackModal(r.fallbackPrompt);openFallbackModal(r.fallbackPrompt)}els.viewCorrectionBtn.textContent="Ver correção";els.viewCorrectionBtn.onclick=()=>renderCorrection(r.corrections||[]);if(state.mode==="guest")loadRanking();window.scrollTo({top:0,behavior:"smooth"})}
function openFallbackModal(promptText){showModal(`<h2>Correção alternativa</h2><p>A IA atingiu o limite. Copie o prompt abaixo e cole em outra IA.</p><textarea class="open-answer" style="min-height:300px">${escapeHtml(promptText)}</textarea><div class="modal-actions"><button class="btn primary" id="closeFallback">Fechar</button></div>`);$("closeFallback").onclick=closeModal}
function renderCorrection(corrections){els.correctionList.classList.remove("hidden");els.correctionList.innerHTML="";corrections.forEach(c=>{const div=document.createElement("div");div.className="correction-card";if(c.kind==="open")div.innerHTML=`<strong>${c.order}. Aberta — nota ${c.score}/${c.maxScore}</strong><p>${escapeHtml(c.prompt)}</p><p><b>Comentário:</b> ${escapeHtml(c.comment||"Sem comentário.")}</p>`;else{const selected=c.options?.find(o=>o.id===c.selectedOptionId)?.text||"Não marcada";const correct=c.options?.find(o=>o.id===c.correctOptionId)?.text||"—";div.innerHTML=`<strong>${c.order}. Fechada — ${c.isCorrect?"correta":"incorreta"}</strong><p>${escapeHtml(c.prompt)}</p><p><b>Sua resposta:</b> ${escapeHtml(selected)}</p><p><b>Correta:</b> ${escapeHtml(correct)}</p>`}els.correctionList.appendChild(div)})}
els.newAttemptBtn.onclick=()=>showDashboard();els.rankingBtn.onclick=loadRanking;
async function loadRanking(){try{const res=await api("/api/ranking");els.rankingPanel.classList.remove("hidden");els.rankingList.innerHTML="";(res.ranking||[]).forEach((r,i)=>{const div=document.createElement("div");div.className="rank-card";div.innerHTML=`<strong>${i+1}. ${escapeHtml(r.displayName)}</strong><p>Nota recente: ${r.latestScore} · Coeficiente: ${r.coefficient} · Tentativas: ${r.attempts}</p><button class="btn" data-user="${r.userId}">Ver abertas</button>`;div.querySelector("button").onclick=()=>loadOpenAnswers(r.userId);els.rankingList.appendChild(div)})}catch(e){alert(friendlyError(e))}}
async function loadOpenAnswers(userId){try{const res=await api(`/api/ranking/open-answers?userId=${encodeURIComponent(userId)}`);const html=(res.items||[]).map(x=>`<div class="correction-card"><strong>${escapeHtml(x.displayName)} — ${x.score}/${x.maxScore}</strong><p>${escapeHtml(x.prompt)}</p><p><b>Resposta:</b> ${escapeHtml(x.answerText)}</p><p><b>Comentário:</b> ${escapeHtml(x.comment||"Sem comentário.")}</p></div>`).join("")||"<p>Nenhuma resposta aberta encontrada.</p>";showModal(`<h2>Respostas abertas</h2>${html}<div class="modal-actions"><button class="btn primary" id="closeOpen">Fechar</button></div>`);$("closeOpen").onclick=closeModal}catch(e){alert(friendlyError(e))}}
async function restoreGuest(){try{const raw=localStorage.getItem("tge_guest_session");if(!raw){hideGuestFeatures();return}const s=JSON.parse(raw);state.token=s.token;state.user=s.user;state.mode="guest";enableGuestFeatures();showDashboard()}catch{hideGuestFeatures()}}
els.chatButton.onclick=()=>{if(state.mode!=="guest")return;state.chatOpen=!state.chatOpen;els.chatWindow.classList.toggle("hidden",!state.chatOpen);if(state.chatOpen)loadChat()};els.closeChatBtn.onclick=()=>{state.chatOpen=false;els.chatWindow.classList.add("hidden")};
els.chatForm.onsubmit=async e=>{e.preventDefault();const body=normalizeName(els.chatInput.value);if(!body)return;try{await api("/api/chat/send",{method:"POST",body:JSON.stringify({body})});els.chatInput.value="";await loadChat()}catch(err){alert(friendlyError(err))}};
async function loadUnread(){if(state.mode!=="guest"||!state.token)return;try{const res=await api("/api/chat/unread");const unread=res.unread||0;els.chatBadge.textContent=unread;els.chatBadge.classList.toggle("hidden",unread<1)}catch{}}
async function loadChat(silent=false){if(state.mode!=="guest"||!state.token)return;try{const res=await api("/api/chat/list");const sig=JSON.stringify((res.messages||[]).map(m=>[m.id,m.body]));if(silent&&sig===state.lastChatRender)return;state.lastChatRender=sig;els.chatMessages.innerHTML="";let lastUser=null;(res.messages||[]).forEach(m=>{const mine=m.userId===state.user.id,same=lastUser===m.userId,row=document.createElement("div");row.className="msg-row"+(mine?" mine":"");const avatar=!mine&&!same?`<div class="avatar">${escapeHtml((m.displayName||"?")[0])}</div>`:(!mine?"<div></div>":"");const name=!mine&&!same?`<div class="msg-name">${escapeHtml(m.displayName)}</div>`:"";row.innerHTML=`${avatar}<div>${name}<button class="bubble" data-id="${m.id}">${escapeHtml(m.body)}</button></div>`;row.querySelector(".bubble").onclick=()=>showReaders(m.id,mine);els.chatMessages.appendChild(row);lastUser=m.userId});els.chatMessages.scrollTop=els.chatMessages.scrollHeight;await loadUnread()}catch(e){if(!silent)alert(friendlyError(e))}}
async function showReaders(messageId,mine){if(!messageId)return;if(!mine){try{await api("/api/chat/mark-read",{method:"POST",body:JSON.stringify({messageId})});await loadUnread()}catch{}}try{const res=await api(`/api/chat/readers?messageId=${encodeURIComponent(messageId)}`);const readers=(res.readers||[]).map(x=>escapeHtml(x.displayName)).join(", ")||"Ninguém visualizou ainda.";showModal(`<h2>Visualizações</h2><p>${readers}</p><div class="modal-actions"><button class="btn primary" id="closeReaders">Fechar</button></div>`);$("closeReaders").onclick=closeModal}catch(e){alert(friendlyError(e))}}
restoreGuest();