export async function onRequest(context){
  const {request,env}=context;
  const url=new URL(request.url);
  const path=url.pathname.replace(/^\/api\/?/,"");
  const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"Content-Type, Authorization","Access-Control-Allow-Methods":"GET, POST, PATCH, OPTIONS"};
  if(request.method==="OPTIONS")return new Response(null,{headers:cors});
  const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{...cors,"Content-Type":"application/json; charset=utf-8"}});
  const fail=(msg,status=400)=>json({error:msg},status);
  try{
    const db=supabase(env);
    if(path==="login"&&request.method==="POST")return json(await login(request,env,db));
    if(path==="visitor/start"&&request.method==="POST")return json(await visitorStart(request,db));
    if(path==="visitor/check"&&request.method==="POST")return json(await visitorCheck(request,db));
    if(path==="attempt/start"&&request.method==="POST")return json(await guestStart(request,env,db));
    if(path==="attempt/answer"&&request.method==="POST")return json(await guestAnswer(request,env,db));
    if(path==="attempt/finish"&&request.method==="POST")return json(await guestFinish(request,env,db));
    if(path==="ranking"&&request.method==="GET")return json(await ranking(request,env,db));
    if(path==="ranking/open-answers"&&request.method==="GET")return json(await rankingOpenAnswers(request,env,db,url));
    if(path==="chat/send"&&request.method==="POST")return json(await chatSend(request,env,db));
    if(path==="chat/list"&&request.method==="GET")return json(await chatList(request,env,db));
    if(path==="chat/unread"&&request.method==="GET")return json(await chatUnread(request,env,db));
    if(path==="chat/mark-read"&&request.method==="POST")return json(await chatMarkRead(request,env,db));
    if(path==="chat/readers"&&request.method==="GET")return json(await chatReaders(request,env,db,url));
    if(path==="admin/logs"&&request.method==="POST")return json(await adminLogs(request,env,db));
    return fail("Caminho não encontrado.",404);
  }catch(e){console.error(e);return fail(translateError(e),500)}
}
function translateError(e){const raw=String(e?.message||e||"");if(raw.includes("quota")||raw.includes("rate")||raw.includes("429"))return"A IA atingiu o limite por enquanto.";if(raw.includes("JWT")||raw.includes("token"))return"Sua sessão expirou. Entre novamente.";if(raw.includes("permission denied"))return"O Supabase recusou a permissão. Confira se a secret key correta está no Cloudflare.";if(raw.includes("Supabase"))return"Supabase não configurado corretamente.";if(raw.includes("fetch"))return"Não consegui conectar ao servidor agora.";return raw&&raw.length<160?raw:"O sistema encontrou um problema. Tente novamente."}
function supabase(env){const base=env.SUPABASE_URL,key=env.SUPABASE_SERVICE_ROLE_KEY;if(!base||!key)throw new Error("Supabase não configurado corretamente.");async function req(method,table,{body=null,query=""}={}){const res=await fetch(`${base}/rest/v1/${table}${query}`,{method,headers:{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json",Prefer:"return=representation"},body:body?JSON.stringify(body):undefined});const txt=await res.text();let data=null;try{data=txt?JSON.parse(txt):null}catch(e){data=txt}if(!res.ok)throw new Error(data?.message||"Erro no banco de dados.");return data}async function rpc(name,body){const res=await fetch(`${base}/rest/v1/rpc/${name}`,{method:"POST",headers:{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify(body||{})});const txt=await res.text();let data=null;try{data=txt?JSON.parse(txt):null}catch(e){data=txt}if(!res.ok)throw new Error(data?.message||"Erro ao executar função no banco.");return data}return{req,rpc}}
async function body(request){try{return await request.json()}catch(e){return{}}}
function normName(s){return String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim()}
function b64(str){return btoa(unescape(encodeURIComponent(str))).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"")}
function b64buf(buf){return btoa(String.fromCharCode(...new Uint8Array(buf))).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"")}
function atoburl(str){str=str.replace(/-/g,"+").replace(/_/g,"/");return decodeURIComponent(escape(atob(str)))}
async function sign(payload,secret){const enc=new TextEncoder();const header=b64(JSON.stringify({alg:"HS256",typ:"JWT"}));const data=b64(JSON.stringify({...payload,exp:Date.now()+1000*60*60*24*30}));const key=await crypto.subtle.importKey("raw",enc.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const sig=await crypto.subtle.sign("HMAC",key,enc.encode(`${header}.${data}`));return`${header}.${data}.${b64buf(sig)}`}
async function verify(request,env){const auth=request.headers.get("Authorization")||"",token=auth.replace(/^Bearer\s+/i,"");if(!token)throw new Error("Você precisa entrar novamente.");const[h,p,s]=token.split(".");const enc=new TextEncoder();const key=await crypto.subtle.importKey("raw",enc.encode(env.SESSION_SECRET||"dev-secret"),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const sig=await crypto.subtle.sign("HMAC",key,enc.encode(`${h}.${p}`));if(b64buf(sig)!==s)throw new Error("Sua sessão expirou. Entre novamente.");const payload=JSON.parse(atoburl(p));if(payload.exp<Date.now())throw new Error("Sua sessão expirou. Entre novamente.");return payload}
async function login(request,env,db){const b=await body(request);const rows=await db.rpc("verify_tge_guest_login",{p_name:normName(b.name),p_password:String(b.password||"")});const user=Array.isArray(rows)?rows[0]:rows;if(!user||!user.user_id)throw new Error("Nome ou senha incorretos.");const token=await sign({id:user.user_id,displayName:user.display_name,role:user.role},env.SESSION_SECRET||"dev-secret");return{token,user:{id:user.user_id,displayName:user.display_name,role:user.role}}}
async function fetchQuestions(db,kind){const qs=await db.req("GET","tge_questions",{query:`?kind=eq.${kind}&active=eq.true&select=*`});if(kind==="closed"){const ids=qs.map(q=>q.id);const opts=ids.length?await db.req("GET","tge_options",{query:`?question_id=in.(${ids.join(",")})&select=id,question_id,text,is_correct`}):[];const by={};opts.forEach(o=>{by[o.question_id]=by[o.question_id]||[];by[o.question_id].push(o)});qs.forEach(q=>q.options=shuffle(by[q.id]||[]))}return qs}
function selectAdaptive(questions,stats,n){stats=stats||{};const unseen=questions.filter(q=>!stats[q.id]);const wrong=questions.filter(q=>(stats[q.id]?.wrong||0)>0);const slow=[...questions].sort((a,b)=>(stats[b.id]?.totalTime||0)-(stats[a.id]?.totalTime||0));const picked=[];const add=list=>{for(const q of shuffle(list)){if(picked.length<n&&!picked.find(x=>x.id===q.id))picked.push(q)}};add(unseen);add(wrong);add(slow);add(questions);return picked.slice(0,n)}
function clientQuestion(q,i){if(q.kind==="open")return{id:q.id,kind:"open",prompt:q.prompt,locked:false,order:i+1,viewStartedAt:Date.now()};return{id:q.id,kind:"closed",prompt:q.prompt,options:shuffle(q.options||[]).map(o=>({id:o.id,text:o.text})),locked:false,order:i+1,viewStartedAt:Date.now()}}
async function visitorStart(request,db){const b=await body(request);const closed=await fetchQuestions(db,"closed");if(closed.length<1)throw new Error("Nenhuma questão fechada ativa foi encontrada.");const selected=selectAdaptive(closed,b.seen||{},20);return{attempt:{id:"visitor-"+crypto.randomUUID(),mode:"visitor",questions:selected.map((q,i)=>clientQuestion(q,i))}}}
async function visitorCheck(request,db){const b=await body(request);const opts=await db.req("GET","tge_options",{query:`?question_id=eq.${b.questionId}&is_correct=eq.true&select=id`});const correct=opts[0]?.id;return{isCorrect:correct===b.selectedOptionId,correctOptionId:correct}}
async function loadUserStats(db,userId){const attempts=await db.req("GET","tge_attempts",{query:`?user_id=eq.${userId}&select=id`});const ids=attempts.map(a=>a.id);if(!ids.length)return{closed:{},open:{}};const rows=await db.req("GET","tge_attempt_questions",{query:`?attempt_id=in.(${ids.join(",")})&select=question_id,kind,is_correct,open_score,time_ms`});const out={closed:{},open:{}};rows.forEach(r=>{const bag=r.kind==="open"?out.open:out.closed;bag[r.question_id]=bag[r.question_id]||{seen:0,wrong:0,totalTime:0};bag[r.question_id].seen++;bag[r.question_id].totalTime+=r.time_ms||0;if(r.kind==="closed"&&!r.is_correct)bag[r.question_id].wrong++;if(r.kind==="open"&&Number(r.open_score||0)<1.2)bag[r.question_id].wrong++});return out}
async function guestStart(request,env,db){const user=await verify(request,env);const attempts=await db.req("GET","tge_attempts",{query:`?user_id=eq.${user.id}&select=id,has_open_questions`});const openDone=attempts.filter(a=>a.has_open_questions).length;const includeOpen=user.role==="admin"||openDone<2;const closedCount=includeOpen?10:20;const openCount=includeOpen?10:0;const history=await loadUserStats(db,user.id);const closed=selectAdaptive(await fetchQuestions(db,"closed"),history.closed,closedCount).map(q=>({...q,kind:"closed"}));const open=openCount?selectAdaptive(await fetchQuestions(db,"open"),history.open,openCount).map(q=>({...q,kind:"open"})):[];const mixed=shuffle([...closed,...open]);const attempt=(await db.req("POST","tge_attempts",{body:{user_id:user.id,mode:"guest",has_open_questions:includeOpen,status:"in_progress",started_at:new Date().toISOString()}}))[0];const questions=[];for(let i=0;i<mixed.length;i++){const q=mixed[i];const row=(await db.req("POST","tge_attempt_questions",{body:{attempt_id:attempt.id,question_id:q.id,order_index:i+1,kind:q.kind,status:"draft"}}))[0];questions.push({...clientQuestion(q,i),attemptQuestionId:row.id})}return{attempt:{id:attempt.id,mode:"guest",questions}}}
async function guestAnswer(request,env,db){await verify(request,env);const b=await body(request);const aq=(await db.req("GET","tge_attempt_questions",{query:`?id=eq.${b.questionAttemptId}&select=*`}))[0];if(!aq)throw new Error("Questão não encontrada.");if(aq.status==="locked")throw new Error("Esta resposta já foi travada.");const patch={status:"locked",time_ms:b.timeMs||0};if(b.kind==="closed"){const correct=(await db.req("GET","tge_options",{query:`?question_id=eq.${aq.question_id}&is_correct=eq.true&select=id`}))[0]?.id;patch.selected_option_id=b.selectedOptionId;patch.is_correct=correct===b.selectedOptionId;patch.closed_score=patch.is_correct?1:0;await db.req("PATCH","tge_attempt_questions",{query:`?id=eq.${aq.id}`,body:patch});return{question:{locked:true,resultKnown:true,isCorrect:patch.is_correct,correctOptionId:correct,selectedOptionId:b.selectedOptionId,timeMs:patch.time_ms}}}patch.answer_text=String(b.answerText||"").slice(0,1200);await db.req("PATCH","tge_attempt_questions",{query:`?id=eq.${aq.id}`,body:patch});return{question:{locked:true,answerText:patch.answer_text,timeMs:patch.time_ms}}}
async function guestFinish(request,env,db){const user=await verify(request,env);const b=await body(request);const rows=await db.req("GET","tge_attempt_questions",{query:`?attempt_id=eq.${b.attemptId}&select=*,tge_questions(*)`});if(rows.some(r=>r.status!=="locked"))throw new Error("Responda todas as questões antes de finalizar.");let fallbackPrompt=null;const openRows=rows.filter(r=>r.kind==="open");if(openRows.length){try{const aiResults=await correctOpenWithAI(openRows,env,db,b.attemptId);for(const r of aiResults){await db.req("PATCH","tge_attempt_questions",{query:`?id=eq.${r.attemptQuestionId}`,body:{open_score:r.score,ai_comment:r.comment,ai_status:"corrected"}})}}catch(e){fallbackPrompt=buildFallbackPrompt(openRows,rows);for(const r of openRows){await db.req("PATCH","tge_attempt_questions",{query:`?id=eq.${r.id}`,body:{open_score:0,ai_comment:"A IA atingiu o limite. Use o botão de correção alternativa.",ai_status:"ai_limit"}})}await db.req("POST","ai_provider_logs",{body:{provider_name:"fallback",status:"limit_or_error",message:translateError(e),attempt_id:b.attemptId,created_at:new Date().toISOString()}})}}const fresh=await db.req("GET","tge_attempt_questions",{query:`?attempt_id=eq.${b.attemptId}&select=*,tge_questions(*)`});const result=await buildResult(db,fresh,fallbackPrompt);await db.req("PATCH","tge_attempts",{query:`?id=eq.${b.attemptId}`,body:{status:"finished",finished_at:new Date().toISOString(),score:result.score,coefficient:result.coefficient,total_time_ms:result.totalTimeMs}});result.attemptNumber=(await db.req("GET","tge_attempts",{query:`?user_id=eq.${user.id}&select=id`})).length;return{result}}
async function buildResult(db,rows,fallbackPrompt=null){const closed=rows.filter(r=>r.kind==="closed"),open=rows.filter(r=>r.kind==="open");const closedScore=closed.reduce((s,r)=>s+(r.closed_score||0),0);const openScore=open.reduce((s,r)=>s+Number(r.open_score||0),0);const closedTotal=closed.length,openTotal=open.length*2,max=closedTotal+openTotal,raw=closedScore+openScore;const score=max?Math.round(raw/max*100)/10:0;const totalTimeMs=rows.reduce((s,r)=>s+(r.time_ms||0),0);const avg=(totalTimeMs/1000)/Math.max(1,rows.length);let tf=1;if(avg<6)tf=.62;else if(avg<14)tf=.82;else if(avg<=95)tf=1.04;else if(avg<=190)tf=.96;else tf=.82;const coefficient=max?Math.round(raw/max*100*tf*(open.length?1.08:1)*10)/10:0;const qids=closed.map(r=>r.question_id);let opts=[];if(qids.length)opts=await db.req("GET","tge_options",{query:`?question_id=in.(${qids.join(",")})&select=id,question_id,text,is_correct`});const by={};opts.forEach(o=>{by[o.question_id]=by[o.question_id]||[];by[o.question_id].push({id:o.id,text:o.text,isCorrect:o.is_correct})});const corrections=rows.sort((a,b)=>a.order_index-b.order_index).map(r=>{const options=by[r.question_id]||[];const correct=options.find(o=>o.isCorrect)?.id||null;return{order:r.order_index,kind:r.kind,prompt:r.tge_questions.prompt,score:r.kind==="open"?Number(r.open_score||0):r.closed_score,maxScore:r.kind==="open"?2:1,comment:r.ai_comment,answerText:r.answer_text,selectedOptionId:r.selected_option_id,correctOptionId:correct,isCorrect:r.is_correct,options:options.map(o=>({id:o.id,text:o.text}))}});return{score,closedScore,closedTotal,openScore,openTotal,coefficient,avgTimeMs:rows.length?totalTimeMs/rows.length:0,totalTimeMs,fallbackPrompt,corrections}}
async function ranking(request,env,db){await verify(request,env);const rows=await db.req("GET","tge_attempts",{query:"?status=eq.finished&select=id,user_id,score,coefficient,total_time_ms,finished_at,invited_users(display_name)&order=finished_at.desc"});const map=new Map();rows.forEach(r=>{const id=r.user_id;if(!map.has(id))map.set(id,{userId:id,displayName:r.invited_users?.display_name||"Usuário",attempts:0,latestScore:0,coefs:[]});const x=map.get(id);x.attempts++;if(x.attempts===1)x.latestScore=r.score;x.coefs.push(Number(r.coefficient||0))});return{ranking:[...map.values()].map(x=>({...x,coefficient:Math.round(x.coefs.reduce((a,b)=>a+b,0)/x.coefs.length*10)/10})).sort((a,b)=>b.coefficient-a.coefficient)}}
async function rankingOpenAnswers(request,env,db,url){await verify(request,env);const userId=url.searchParams.get("userId");const attempts=await db.req("GET","tge_attempts",{query:`?user_id=eq.${userId}&status=eq.finished&select=id,invited_users(display_name)&order=finished_at.desc&limit=3`});const ids=attempts.map(a=>a.id);if(!ids.length)return{items:[]};const rows=await db.req("GET","tge_attempt_questions",{query:`?attempt_id=in.(${ids.join(",")})&kind=eq.open&select=*,tge_questions(prompt)`});return{items:rows.map(r=>({displayName:attempts[0].invited_users?.display_name||"Usuário",prompt:r.tge_questions.prompt,answerText:r.answer_text,score:Number(r.open_score||0),maxScore:2,comment:r.ai_comment}))}}
async function chatSend(request,env,db){const user=await verify(request,env);const b=await body(request);const msg=String(b.body||"").trim().slice(0,500);if(!msg)throw new Error("Escreva uma mensagem.");const row=(await db.req("POST","chat_messages",{body:{user_id:user.id,body:msg,created_at:new Date().toISOString()}}))[0];return{message:row}}
async function chatList(request,env,db){const user=await verify(request,env);const rows=await db.req("GET","chat_messages",{query:"?select=id,user_id,body,created_at,invited_users(display_name)&order=created_at.asc&limit=160"});for(const m of rows){if(m.user_id!==user.id){try{await db.req("POST","chat_reads",{body:{message_id:m.id,user_id:user.id,read_at:new Date().toISOString()}})}catch(e){}}}return{messages:rows.map(r=>({id:r.id,userId:r.user_id,displayName:r.invited_users?.display_name||"Usuário",body:r.body,createdAt:r.created_at}))}}
async function chatUnread(request,env,db){const user=await verify(request,env);const rows=await db.req("GET","chat_messages",{query:`?user_id=neq.${user.id}&select=id`});const ids=rows.map(r=>r.id);if(!ids.length)return{unread:0};const reads=await db.req("GET","chat_reads",{query:`?user_id=eq.${user.id}&message_id=in.(${ids.join(",")})&select=message_id`});const seen=new Set(reads.map(r=>r.message_id));return{unread:ids.filter(id=>!seen.has(id)).length}}
async function chatMarkRead(request,env,db){const user=await verify(request,env);const b=await body(request);const msg=(await db.req("GET","chat_messages",{query:`?id=eq.${b.messageId}&select=user_id`}))[0];if(!msg||msg.user_id===user.id)return{ok:true};try{await db.req("POST","chat_reads",{body:{message_id:b.messageId,user_id:user.id,read_at:new Date().toISOString()}})}catch(e){}return{ok:true}}
async function chatReaders(request,env,db,url){const user=await verify(request,env);const messageId=url.searchParams.get("messageId");const msg=(await db.req("GET","chat_messages",{query:`?id=eq.${messageId}&select=user_id`}))[0];if(!msg)throw new Error("Mensagem não encontrada.");if(msg.user_id!==user.id)await chatMarkRead(new Request(request.url,{method:"POST",headers:request.headers,body:JSON.stringify({messageId})}),env,db);const rows=await db.req("GET","chat_reads",{query:`?message_id=eq.${messageId}&select=read_at,invited_users(display_name)`});return{readers:rows.filter(r=>r.invited_users?.display_name).map(r=>({displayName:r.invited_users.display_name,readAt:r.read_at}))}}
async function adminLogs(request,env,db){const b=await body(request);if(!env.ADMIN_LOG_PASSWORD||b.password!==env.ADMIN_LOG_PASSWORD)throw new Error("Senha administrativa incorreta.");const logs=await db.req("GET","ai_provider_logs",{query:"?select=*&order=created_at.desc&limit=150"});return{logs}}
async function correctOpenWithAI(openRows,env,db,attemptId){const prompt=buildCorrectionPrompt(openRows);let providers=[];try{providers=JSON.parse(env.LLM_PROVIDERS_JSON||"[]")}catch(e){throw new Error("A lista de IAs está mal configurada no Cloudflare.")}providers=providers.sort((a,b)=>(a.priority||99)-(b.priority||99));if(!providers.length)throw new Error("Nenhuma IA foi configurada no Cloudflare.");let lastError=null;for(const provider of providers){try{const text=await callProvider(provider,prompt);const parsed=parseJson(text);if(!parsed.results||!Array.isArray(parsed.results))throw new Error("A IA respondeu fora do formato esperado.");await db.req("POST","ai_provider_logs",{body:{provider_name:provider.name||provider.type,status:"ok",message:"Correção realizada com sucesso.",attempt_id:attemptId,created_at:new Date().toISOString()}});return openRows.map(row=>{const found=parsed.results.find(x=>x.attemptQuestionId===row.id||x.questionId===row.question_id)||{};return{attemptQuestionId:row.id,score:Math.max(0,Math.min(2,Number(found.score||0))),comment:String(found.comment||"Comentário não informado pela IA.").slice(0,180)}})}catch(e){lastError=e;await db.req("POST","ai_provider_logs",{body:{provider_name:provider.name||provider.type||"IA",status:"error",message:translateError(e),attempt_id:attemptId,created_at:new Date().toISOString()}})}}throw lastError||new Error("Todas as IAs falharam.")}
function buildCorrectionPrompt(rows){const payload=rows.map(r=>({attemptQuestionId:r.id,questionId:r.question_id,question:r.tge_questions.prompt,expected:r.tge_questions.expected_answer,rubric:r.tge_questions.rubric,answer:r.answer_text,timeMs:r.time_ms}));return`Você é corretor de Teoria Geral do Estado. Corrija as respostas abertas de forma objetiva e justa. Cada questão vale de 0 a 2 pontos. Critério fixo: 0 = em branco, fuga total do tema ou erro grave; 0.5 = menciona o tema, mas confunde o conceito central; 1.0 = acerta parcialmente, com lacunas importantes; 1.5 = acerta o conceito central, mas falta precisão, elemento relevante ou exemplo; 2.0 = resposta correta, completa e juridicamente precisa. Use o tempo apenas como indício de resposta vazia, chute ou incoerência. Não premie demora excessiva. Responda SOMENTE JSON válido, sem markdown, sem texto fora do JSON. Formato obrigatório: {"results":[{"attemptQuestionId":"...","questionId":"...","score":1.5,"comment":"Comentário curto em português."}]} Dados: ${JSON.stringify(payload)}`}
function buildFallbackPrompt(openRows,allRows){return buildCorrectionPrompt(openRows)+`\n\nContexto adicional: questões fechadas respondidas: ${allRows.filter(r=>r.kind==="closed").length}. Tempo total aproximado: ${allRows.reduce((s,r)=>s+(r.time_ms||0),0)}ms. Corrija usando o critério acima e devolva JSON no formato pedido.`}
function parseJson(text){const clean=String(text||"").replace(/```json/g,"").replace(/```/g,"").trim();return JSON.parse(clean)}
async function callProvider(provider,prompt){if(provider.type==="gemini")return callGemini(provider,prompt);if(provider.type==="openai_compatible")return callOpenAICompatible(provider,prompt);throw new Error("Tipo de IA não reconhecido.")}
async function callGemini(provider,prompt){const model=provider.model||"gemini-2.0-flash";const res=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${provider.apiKey}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{temperature:.1,maxOutputTokens:1200,responseMimeType:"application/json"}})});const data=await res.json();if(!res.ok)throw new Error(data?.error?.message||"A IA principal não conseguiu corrigir.");return data.candidates?.[0]?.content?.parts?.map(p=>p.text).join("")||""}
async function callOpenAICompatible(provider,prompt){const res=await fetch(provider.baseUrl,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${provider.apiKey}`},body:JSON.stringify({model:provider.model,messages:[{role:"user",content:prompt}],temperature:.1,max_tokens:1200})});const data=await res.json();if(!res.ok)throw new Error(data?.error?.message||"Uma IA reserva não conseguiu corrigir.");return data.choices?.[0]?.message?.content||""}
function shuffle(arr){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
